import logging
import hashlib
from typing import Protocol
import numpy as np

logger = logging.getLogger(__name__)

class EmbeddingProvider(Protocol):
    """
    Protocol defining the interface for all vector embedding generators.
    """
    def embed_text(self, text: str) -> list[float]:
        """Generate vector embedding for a single text input."""
        ...

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        """Generate vector embeddings for a batch of text inputs."""
        ...

    @property
    def dimension(self) -> int:
        """Return the vector space dimension generated by this provider."""
        ...


class MockEmbeddingProvider:
    """
    Deterministic Mock Embedding Provider for local development and testing.
    Generates repeatable pseudo-random float vectors based on text content hash.
    """
    def __init__(self, dimension: int = 1536):
        self._dimension = dimension

    def embed_text(self, text: str) -> list[float]:
        # Generate a deterministic seed from the text hash
        hasher = hashlib.sha256(text.encode('utf-8'))
        seed = int(hasher.hexdigest()[:8], 16)
        rng = np.random.default_rng(seed)
        vector = rng.standard_normal(self._dimension)
        # Normalize to unit length (L2 norm = 1) for cosine similarity compatibility
        norm = np.linalg.norm(vector)
        if norm > 0:
            vector = vector / norm
        return vector.tolist()

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        return [self.embed_text(t) for t in texts]

    @property
    def dimension(self) -> int:
        return self._dimension


class OpenAIEmbeddingProvider:
    """
    Wrapper for OpenAI's Embedding API models.
    Loads client dependencies lazily to avoid import issues when unused.
    """
    def __init__(self, api_key: str, model: str = "text-embedding-3-small", dimension: int = 1536):
        self.api_key = api_key
        self.model = model
        self._dimension = dimension
        self._client = None

    def _get_client(self):
        if self._client is None:
            try:
                import openai
                self._client = openai.OpenAI(api_key=self.api_key)
            except ImportError as e:
                logger.error("OpenAI library not installed. Run 'pip install openai'")
                raise e
        return self._client

    def embed_text(self, text: str) -> list[float]:
        client = self._get_client()
        try:
            response = client.embeddings.create(
                input=[text],
                model=self.model,
                dimensions=self._dimension if "text-embedding-3" in self.model else None
            )
            return response.data[0].embedding
        except Exception as e:
            logger.error(f"Failed generating OpenAI embedding: {e}")
            raise e

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        client = self._get_client()
        try:
            response = client.embeddings.create(
                input=texts,
                model=self.model,
                dimensions=self._dimension if "text-embedding-3" in self.model else None
            )
            return [record.embedding for record in response.data]
        except Exception as e:
            logger.error(f"Failed generating OpenAI batch embeddings: {e}")
            raise e

    @property
    def dimension(self) -> int:
        return self._dimension


class GeminiEmbeddingProvider:
    """
    Wrapper for Google Gemini's Embedding API (text-embedding-004).
    Loads dependencies lazily to prevent environment initialization issues.
    """
    def __init__(self, api_key: str, model: str = "models/text-embedding-004", dimension: int = 768):
        self.api_key = api_key
        self.model = model
        self._dimension = dimension
        self._initialized = False

    def _init_sdk(self):
        if not self._initialized:
            try:
                import google.generativeai as genai
                genai.configure(api_key=self.api_key)
                self._genai = genai
                self._initialized = True
            except ImportError as e:
                logger.error("Google GenerativeAI library not installed. Run 'pip install google-generativeai'")
                raise e

    def embed_text(self, text: str) -> list[float]:
        self._init_sdk()
        try:
            result = self._genai.embed_content(
                model=self.model,
                content=text,
                task_type="retrieval_document",
                output_dimensionality=self._dimension
            )
            return result['embedding']
        except Exception as e:
            logger.error(f"Failed generating Gemini embedding: {e}")
            raise e

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        self._init_sdk()
        try:
            result = self._genai.embed_content(
                model=self.model,
                contents=texts,
                task_type="retrieval_document",
                output_dimensionality=self._dimension
            )
            return result['embedding']
        except Exception as e:
            logger.error(f"Failed generating Gemini batch embeddings: {e}")
            raise e

    @property
    def dimension(self) -> int:
        return self._dimension
